### ISSUE TITLE
Problem running the test app

### ISSUE THREAD

**Issue by vitaly-t** [florisdh/node-wasm#1]
After a successful `wasm` build, cannot start the node app, getting the following error:

![image](https://user-images.githubusercontent.com/5108906/60604492-b3081600-9daf-11e9-9d6c-9d1fa09c4a54.png)

And I followed all installation steps precisely.

**Environment:**

* Node.js 12.6.0
* TypeScript 3.5.2
* Windows 10

**Comment by florisdh** [comment]
Thanks for pointing it out!

Apparently something broke in this setup using the latest assemblyscript version, so I've set it to a fixed version that was working. Please note that assemblyscript might not be stable enough for production yet. :)

Commit:
https://github.com/florisdh/node-wasm/commit/298b75f1d885aba701962689ede3cfc8c170b4ea

You can now update the packages and run the build again:
- git pull origin master
- cd assembly
- npm i
- npm run build

Please let me know if there are other issues :)

**Comment by vitaly-t** [comment]
This now works. Thank you!
